-- Weekly report snapshots: one row per user per calendar week (Mon–Sun),
-- generated by the Sunday cron job (/api/cron/weekly-reports). Storing the
-- computed report — rather than only ever recomputing it live — gives
-- three things the live-only version in reports.ts couldn't:
--   1. A stable "what got emailed" record, so the in-app popup and the
--      email always agree on the same numbers.
--   2. A cheap "does this user have an unseen report" check for the
--      in-app popup, without recomputing anything.
--   3. A history of past weeks, for free, if the report page ever wants
--      to show more than just the latest one.
--
-- `data` holds the same shape as WeeklyReportData (src/actions/reports.ts)
-- as jsonb — denormalized on purpose, since this is a point-in-time
-- snapshot of numbers that may later be revised (e.g. an edited
-- transaction), not a live view.

create table public.weekly_report_snapshots (
  id uuid not null default gen_random_uuid(),
  user_id uuid not null,
  week_start date not null,
  week_end date not null,
  data jsonb not null,
  emailed_at timestamp with time zone,
  seen_at timestamp with time zone,
  created_at timestamp with time zone not null default now(),
  constraint weekly_report_snapshots_pkey primary key (id),
  constraint weekly_report_snapshots_user_id_fkey foreign key (user_id) references auth.users (id),
  -- Re-running the cron for a week that already has a snapshot should
  -- update it, not duplicate it — the action layer upserts on this.
  constraint weekly_report_snapshots_user_week_key unique (user_id, week_start)
);

create index weekly_report_snapshots_user_id_idx on public.weekly_report_snapshots (user_id, week_start desc);
